#!/usr/bin/env bash
# Push one deploy branch per library: deploy/<library> holds that library's finished
# app as index.html at the root, so a Netlify site only needs "Branch to deploy".
set -euo pipefail
cd "$(dirname "$0")/.."
python3 scripts/build_data.py
for dir in dist/*/; do
  lib=$(basename "$dir")
  branch="deploy/$lib"
  tmp=$(mktemp -d)
  cp "$dir/index.html" "$tmp/index.html"
  printf '# Lesko Help %s app\n\nGenerated by scripts/publish_branches.sh. Do not edit; edit the main branch and rerun.\n' "$lib" > "$tmp/README.md"
  git -C "$tmp" init -q -b "$branch"
  git -C "$tmp" -c user.name="Claude" -c user.email="noreply@anthropic.com" add -A
  git -C "$tmp" -c user.name="Claude" -c user.email="noreply@anthropic.com" commit -q -m "Deploy $lib app ($(date -u +%Y-%m-%d))"
  git -C "$tmp" remote add origin "$(git remote get-url origin)"
  git -C "$tmp" push -q --force origin "$branch"
  rm -rf "$tmp"
  echo "pushed $branch"
done
